---
title: "Surrogate_model"
author: "Marcelo Hurtado"
date: "2024-10-09"
output: html_document
---

Load ML functions
```{r setup, include=FALSE}
source("ML_functions.R")
```

Read Sobol samples 
```{r}
sobol_samples = read.csv('Physicell_NLCs-CLL/data_output/Parameter_exploration/samples/Samples_0.csv')
viability = read.csv('Physicell_NLCs-CLL/data_output/Parameter_exploration/results/viability_1.csv')
```

Set data
```{r}
time_point = 1
data = sobol_samples %>%
  mutate(target = as.numeric(t(viability[time_point,])))
```

Set training and testing set
```{r}
index = createDataPartition(data[,"target"], times = 1, p = 0.8, list = FALSE) 
training_set = data[index,]
testing_set = data[-index,]
```

Simulate dataset
```{r}
# Generate 60 samples with 10 features (random normal values)
features <- as.data.frame(matrix(rnorm(100 * 3), nrow = 100, ncol = 5))

# Name the feature columns
colnames(features) <- paste0("feature_", 1:5)

# Generate the target column (random normal values)
features$target <- rnorm(100)
```

ML models
```{r}
x = compute.ML(features, "target", 0.8, stack = T, seed = 123, file_name = "Test")
```


